"""empty message

Revision ID: 6c89a25ee18d
Revises: a8afea82ec3b
Create Date: 2020-06-27 18:55:29.294199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c89a25ee18d'
down_revision = 'a8afea82ec3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_data', 'time_recorded',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_data', 'time_recorded',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
