"""empty message

Revision ID: a8afea82ec3b
Revises: 1641d6a71bdd
Create Date: 2020-06-27 09:10:24.205347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8afea82ec3b'
down_revision = '1641d6a71bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data', 'state')
    # ### end Alembic commands ###
